<?php
require '../includes/connection.php';
require '../vendor/autoload.php';

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use PhpOffice\PhpSpreadsheet\Worksheet\Drawing;

session_start();
if (!isset($_SESSION['MEMBER_ID'])) {
    header("Location: login.php");
    exit();
}

// **Retrieve user details (type & branch)**
$queryUser = "SELECT u.TYPE_ID, u.BRANCH_ID, u.USERNAME, e.FIRST_NAME, e.LAST_NAME 
              FROM users u 
              JOIN employee e ON u.EMPLOYEE_ID = e.EMPLOYEE_ID 
              WHERE u.ID = ?";
$stmtUser = mysqli_prepare($db, $queryUser);
mysqli_stmt_bind_param($stmtUser, "i", $_SESSION['MEMBER_ID']);
mysqli_stmt_execute($stmtUser);
$resultUser = mysqli_stmt_get_result($stmtUser);
$userData = mysqli_fetch_assoc($resultUser);
mysqli_stmt_close($stmtUser);

$userTypeID = $userData['TYPE_ID'] ?? null;
$branchID = $userData['BRANCH_ID'] ?? null;
$generatedBy = "Generated by: " . ($userData['FIRST_NAME'] ?? 'Unknown') . " " . ($userData['LAST_NAME'] ?? 'User');

// **Get selected date range**
$from_date = $_GET['from_date'] ?? date('Y-m-d');
$to_date = $_GET['to_date'] ?? date('Y-m-d');
$from_date_formatted = strtoupper(date("F j, Y", strtotime($from_date)));
$to_date_formatted = strtoupper(date("F j, Y", strtotime($to_date)));
$date_range_text = ($from_date === $to_date) ? "'$from_date_formatted'" : "$from_date_formatted TO $to_date_formatted";
$file_name = strtoupper("$date_range_text.xlsx");

// **Fetch transactions**
$queryTransactions = "SELECT T.TRANS_NO, C.FIRST_NAME, C.LAST_NAME, T.NUMOFITEMS, T.SUBTOTAL, T.CASH, T.payment, T.DATE, B.BRANCH_NAME, T.DISCOUNT
                      FROM transaction T
                      JOIN customer C ON T.CUST_ID = C.CUST_ID
                      JOIN branches B ON C.BRANCH_ID = B.BRANCH_ID
                      WHERE DATE(T.DATE) BETWEEN ? AND ?";


$params = [$from_date, $to_date];
$types = "ss";

if ($userTypeID != 1) { // **Non-admin users only see their branch**
    $queryTransactions .= " AND B.BRANCH_ID = ?";
    $params[] = $branchID;
    $types .= "i";
}

$queryTransactions .= " ORDER BY T.DATE ASC";
$stmtTransactions = mysqli_prepare($db, $queryTransactions);
mysqli_stmt_bind_param($stmtTransactions, $types, ...$params);
mysqli_stmt_execute($stmtTransactions);
$resultTransactions = mysqli_stmt_get_result($stmtTransactions);
mysqli_stmt_close($stmtTransactions);

// **Fetch Current Session Expenses**
$totalExpenses = 0;
$expenses = [];
if (isset($_SESSION['EXPENSE_SESSION_ID'])) {
    $session_id = $_SESSION['EXPENSE_SESSION_ID'];
    
    $queryExpenses = "SELECT expense_name, expense_amount FROM expenses WHERE session_id = ?";
    $stmtExpenses = mysqli_prepare($db, $queryExpenses);
    mysqli_stmt_bind_param($stmtExpenses, "s", $session_id);
    mysqli_stmt_execute($stmtExpenses);
    $resultExpenses = mysqli_stmt_get_result($stmtExpenses);
    
    while ($expense = mysqli_fetch_assoc($resultExpenses)) {
        $expenses[] = $expense;
        $totalExpenses += (float) $expense['expense_amount'];
    }
    
    mysqli_stmt_close($stmtExpenses);
}

// **Create Spreadsheet**
$spreadsheet = new Spreadsheet();
$sheet = $spreadsheet->getActiveSheet();

// **Company Name**
$companyName = "MJC HARDWARE TRADING";
$sheet->setCellValue('A1', $companyName);
$sheet->mergeCells('A1:I1');
$sheet->getStyle('A1')->getFont()->setBold(true)->setSize(16);
$sheet->getStyle('A1')->getAlignment()->setHorizontal('center');

// **Company Logo**
$logoPath = '../img/clogo.png';
if (file_exists($logoPath)) {
    $drawing = new Drawing();
    $drawing->setName('MJC Hardware Logo');
    $drawing->setPath($logoPath);
    $drawing->setCoordinates('B1');
    $drawing->setHeight(90);
    $drawing->setWorksheet($sheet);
}

// **Date Range Title**
$sheet->setCellValue('A3', $date_range_text);
$sheet->mergeCells('A3:I3');
$sheet->getStyle('A3')->getFont()->setBold(true)->setSize(14);
$sheet->getStyle('A3')->getAlignment()->setHorizontal('center');

// **Column Headers**
$headers = ["Transaction Number", "Customer", "# of Items", "Subtotal","Discount","Grand Total", "Cash", "Change", "Payment", "Date", "Branch"];

$sheet->fromArray([$headers], NULL, 'A4');
$sheet->getStyle('A4:I4')->getFont()->setBold(true);

// **Insert Transactions**
$rowIndex = 5;
$totalSubtotal = 0;
while ($row = mysqli_fetch_assoc($resultTransactions)) {
    $cash = (float) str_replace(',', '', $row['CASH'] ?? 0);
    $subtotal = (float) str_replace(',', '', $row['SUBTOTAL'] ?? 0);  
    $discount = (float) str_replace(',', '', $row['DISCOUNT'] ?? 0);  
    $Grandtotal = $subtotal - $discount;  
    $sukli = $cash - $Grandtotal;

    $totalSubtotal += $Grandtotal;

    $sheet->fromArray([
        $row['TRANS_NO'],
        $row['FIRST_NAME'] . ' ' . $row['LAST_NAME'],
        $row['NUMOFITEMS'],
        number_format($subtotal, 2),
        number_format($discount, 2),
        number_format($Grandtotal, 2),
        number_format($cash, 2),
        number_format($sukli, 2),
        $row['payment'],
        date("m/d/Y h:i A", strtotime($row['DATE'])),
        $row['BRANCH_NAME'],
       
    ], NULL, "A$rowIndex");

    $rowIndex++;
}


// **Insert Total Sales**
$sheet->fromArray(["", "","","", "TOTAL SALES", number_format($totalSubtotal, 2), "", "", "", "", ""], NULL, "A$rowIndex");
$rowIndex++;


// **Insert Expenses**
if (!empty($expenses)) {
    $sheet->setCellValue("E$rowIndex", "Expenses");
    $sheet->getStyle("E$rowIndex")->getFont()->setBold(true);
    $rowIndex++;

    foreach ($expenses as $expense) {
        $sheet->fromArray([$expense['expense_name'], number_format($expense['expense_amount'], 2)], NULL, "E$rowIndex");
        $rowIndex++;
    }
}

// **Insert Total Expenses**
$sheet->fromArray(["", "","","", "TOTAL EXPENSES", number_format($totalExpenses, 2), "", "", "", "", ""], NULL, "A$rowIndex");
$sheet->getStyle("E$rowIndex:F$rowIndex")->getFont()->setBold(true);
$rowIndex++;

// **Compute Final Total**
$finalTotal = $totalSubtotal - $totalExpenses;
$sheet->fromArray(["", "","","", "FINAL TOTAL", number_format($finalTotal, 2), "", "", "", "", ""], NULL, "A$rowIndex");
$sheet->getStyle("E$rowIndex:F$rowIndex")->getFont()->setBold(true);
$rowIndex++;
// **Insert Footer**
$rowIndex++;
$rowIndex++;
$sheet->setCellValue("B$rowIndex", "__________________________");
$sheet->setCellValue("F$rowIndex", "__________________________");
$rowIndex++;
$sheet->setCellValue("B$rowIndex", "Checked by:");
$sheet->setCellValue("F$rowIndex", "Approved by:");
$rowIndex += 2;
date_default_timezone_set('Asia/Manila'); // Set to your local timezone if needed
$generationTime = "Generated on: " . date("F j, Y, g:i A");

$rowIndex++;
$sheet->setCellValue("A$rowIndex", "*This is a computer-generated report.*");
$rowIndex++;
$sheet->setCellValue("A$rowIndex", $generatedBy);
$rowIndex++;
$sheet->setCellValue("A$rowIndex", $generationTime);

// **Auto-adjust column width**
foreach (range('A', 'J') as $columnID) {
    $sheet->getColumnDimension($columnID)->setAutoSize(true);
}
// **Clear session variable after export**
unset($_SESSION['EXPENSE_SESSION_ID']);
// **Generate Excel file**
header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
header("Content-Disposition: attachment; filename=\"$file_name\"");
$writer = new Xlsx($spreadsheet);
$writer->save('php://output');
exit;
?>
