<?php
require '../includes/connection.php';
require '../vendor/autoload.php'; // Load PhpSpreadsheet

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use PhpOffice\PhpSpreadsheet\Worksheet\Drawing;

// Start session and check authentication
session_start();
if (!isset($_SESSION['MEMBER_ID'])) {
    header("Location: login.php");
    exit();
}

// Fetch user role and branch
$querya = "SELECT u.TYPE_ID, u.BRANCH_ID FROM users u WHERE u.ID = " . intval($_SESSION['MEMBER_ID']);
$resulta = mysqli_query($db, $querya) or die(mysqli_error($db));

if ($row = mysqli_fetch_assoc($resulta)) {
    $userTypeID = $row['TYPE_ID'];
    $branchID = $row['BRANCH_ID'];
} else {
    die('User not found in database.');
}

// Get selected date range
$from_date = $_GET['from_date'] ?? date('Y-m-d');
$to_date = $_GET['to_date'] ?? date('Y-m-d');

$from_date_formatted = strtoupper(date("F j, Y", strtotime($from_date)));
$to_date_formatted = strtoupper(date("F j, Y", strtotime($to_date)));

if ($from_date === $to_date) {
    $date_range_text = "'$from_date_formatted'";
    $file_name = strtoupper("$from_date_formatted.xlsx");
} else {
    $date_range_text = "$from_date_formatted TO $to_date_formatted";
    $file_name = strtoupper("$from_date_formatted TO $to_date_formatted Product.xlsx");
}

// **Fetch Current Session Expenses**
$totalExpenses = 0;
$expenses = [];
if (isset($_SESSION['EXPENSE_SESSION_ID'])) {
    $session_id = $_SESSION['EXPENSE_SESSION_ID'];
    
    $queryExpenses = "SELECT expense_name, expense_amount FROM expenses WHERE session_id = ?";
    $stmtExpenses = mysqli_prepare($db, $queryExpenses);
    mysqli_stmt_bind_param($stmtExpenses, "s", $session_id);
    mysqli_stmt_execute($stmtExpenses);
    $resultExpenses = mysqli_stmt_get_result($stmtExpenses);
    
    while ($expense = mysqli_fetch_assoc($resultExpenses)) {
        $expenses[] = $expense;
        $totalExpenses += (float) $expense['expense_amount'];
    }
    
    mysqli_stmt_close($stmtExpenses);
}


// **Retrieve user details (type & branch)**
$queryUser = "SELECT u.TYPE_ID, u.BRANCH_ID, u.USERNAME, e.FIRST_NAME, e.LAST_NAME 
              FROM users u 
              JOIN employee e ON u.EMPLOYEE_ID = e.EMPLOYEE_ID 
              WHERE u.ID = ?";
$stmtUser = mysqli_prepare($db, $queryUser);
mysqli_stmt_bind_param($stmtUser, "i", $_SESSION['MEMBER_ID']);
mysqli_stmt_execute($stmtUser);
$resultUser = mysqli_stmt_get_result($stmtUser);
$userData = mysqli_fetch_assoc($resultUser);
mysqli_stmt_close($stmtUser);

$userTypeID = $userData['TYPE_ID'] ?? null;
$branchID = $userData['BRANCH_ID'] ?? null;
$generatedBy = "Generated by: " . ($userData['FIRST_NAME'] ?? 'Unknown') . " " . ($userData['LAST_NAME'] ?? 'User');

// Create a new Spreadsheet
$spreadsheet = new Spreadsheet();
$sheet = $spreadsheet->getActiveSheet();

// Insert Company Logo
$logoPath = '../img/clogo.png'; // Update with actual logo path
if (file_exists($logoPath)) {
    $drawing = new Drawing();
    $drawing->setName('MJC Hardware Logo');
    $drawing->setPath($logoPath);
    $drawing->setCoordinates('B1'); // Position logo
    $drawing->setHeight(80); // Adjust height as needed
    $drawing->setWorksheet($sheet);
}

// Insert Company Name
$companyName = "MJC HARDWARE TRADING";
$sheet->setCellValue('B1', $companyName);
$sheet->mergeCells('B1:G1'); // Merge cells for alignment
$sheet->getStyle('B1')->getFont()->setBold(true)->setSize(16);
$sheet->getStyle('B1')->getAlignment()->setHorizontal('center');

// Insert Date Range Below Company Name
$sheet->setCellValue('B2', $date_range_text);
$sheet->mergeCells('B2:G2');
$sheet->getStyle('B2')->getFont()->setBold(true)->setSize(12);
$sheet->getStyle('B2')->getAlignment()->setHorizontal('center');

// Column Headers
$headers = ["Products", "Description", "Quantity", "Price", "Subtotal"];
$sheet->fromArray([$headers], NULL, 'B4');
$sheet->getStyle('B4:F4')->getFont()->setBold(true);

// Fetch transaction details
$query = "SELECT TD.PRODUCTS, TD.DESCRIPTION, TD.QTY, TD.PRICE, (TD.QTY * TD.PRICE) AS SUBTOTAL
          FROM transaction_details TD
          JOIN transaction T ON TD.TRANS_NO = T.TRANS_NO
          JOIN customer C ON T.CUST_ID = C.CUST_ID
          JOIN branches B ON C.BRANCH_ID = B.BRANCH_ID
          WHERE DATE(T.DATE) BETWEEN '" . mysqli_real_escape_string($db, $from_date) . "' 
                                AND '" . mysqli_real_escape_string($db, $to_date) . "'";

if ($userTypeID != 1) { // If NOT admin, filter by branch
    $query .= " AND B.BRANCH_ID = " . intval($branchID);
}

$query .= " ORDER BY TD.PRODUCTS ASC";
$result = mysqli_query($db, $query) or die(mysqli_error($db));

$rowIndex = 5;
$totalSubtotal = 0;

while ($row = mysqli_fetch_assoc($result)) {
    $subtotal = (float) $row['SUBTOTAL'];
    $totalSubtotal += $subtotal;

    // Fill row with data including description
    $sheet->fromArray([
        $row['PRODUCTS'],
        $row['DESCRIPTION'],
        number_format($row['QTY'], 2),
        number_format($row['PRICE'], 2),
        number_format($subtotal, 2)
    ], NULL, "B$rowIndex");

    $rowIndex++;
}

// **Insert Expenses**
if (!empty($expenses)) {
    $rowIndex++; // Add spacing row
    $sheet->setCellValue("C$rowIndex", "Current Session Expenses");
    $sheet->getStyle("C$rowIndex")->getFont()->setBold(true);
    $rowIndex++;

    foreach ($expenses as $expense) {
        $sheet->fromArray([$expense['expense_name'], number_format($expense['expense_amount'], 2)], NULL, "C$rowIndex");
        $sheet->getStyle("D$rowIndex")->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_RIGHT);
        $rowIndex++;
    }
}

// **Insert Total Expenses**
$sheet->fromArray(["", "", "TOTAL EXPENSES", number_format($totalExpenses, 2)], NULL, "C$rowIndex");
$sheet->getStyle("C$rowIndex:D$rowIndex")->getFont()->setBold(true);
$sheet->getStyle("D$rowIndex")->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_RIGHT);
$rowIndex++;

// **Compute Final Total**
$finalTotal = $totalSubtotal - $totalExpenses;
$sheet->fromArray(["", "", "FINAL TOTAL", number_format($finalTotal, 2)], NULL, "C$rowIndex");
$sheet->getStyle("C$rowIndex:D$rowIndex")->getFont()->setBold(true);
$sheet->getStyle("D$rowIndex")->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_RIGHT);

// **Insert Footer**
$rowIndex++;
$rowIndex++;
$sheet->setCellValue("B$rowIndex", "__________________________");
$sheet->setCellValue("F$rowIndex", "__________________________");
$rowIndex++;
$sheet->setCellValue("B$rowIndex", "Checked by:");
$sheet->setCellValue("F$rowIndex", "Approved by:");
$rowIndex += 2;
date_default_timezone_set('Asia/Manila'); // Set to your local timezone if needed
$generationTime = "Generated on: " . date("F j, Y, g:i A");

$rowIndex++;
$sheet->setCellValue("A$rowIndex", "*This is a computer-generated report.*");
$rowIndex++;
$sheet->setCellValue("A$rowIndex", $generatedBy);
$rowIndex++;
$sheet->setCellValue("A$rowIndex", $generationTime);


// Auto-adjust column width for data columns
foreach (range('B', 'E') as $columnID) {
    $sheet->getColumnDimension($columnID)->setAutoSize(true);
}

// Generate Excel file
header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
header("Content-Disposition: attachment; filename=\"$file_name\"");
header('Cache-Control: max-age=0');
// **Clear session variable after export**
unset($_SESSION['EXPENSE_SESSION_ID']);
$writer = new Xlsx($spreadsheet);
$writer->save('php://output');
exit;

?>
